# GET lista de users
GET http://localhost:3000/api/v1/users
Accept: application/json
Stripe-Version: 2025-01-01

###

GET http://localhost:3000/api/v1/users/1
Accept: application/json
Stripe-Version: 2023-10-01

###

POST http://localhost:3000/api/v1/users
Content-Type: application/json
Accept: application/json

{
  "user": {
    "first_name": "Diego",
    "last_name": "Vivar",
    "email": "diego@example.com"
  }
}

###

PATCH http://localhost:3000/api/v1/users/1
Content-Type: application/json
Accept: application/json
Stripe-Version: 2024-05-15

{
  "user": {
    "first_name": "Juan Updated"
  }
}

###

DELETE http://localhost:3000/api/v1/users/1
Accept: application/json
